---
# tasks file for cleanup_execution_host

- name: Cleanup "{{ image_conversion_dir }}/image_conversion/" directory and its contents
  ansible.builtin.file:
    path: "{{ image_conversion_dir }}/image_conversion"
    state: absent

# - name: Notify shareholders of Image Completion
#   community.general.mail:
#     host: 
#     port: 25
#     from:
#     to: "{{ notify_users }}"
#     subject: "The New Provisioned {{ provisioned_image_name }} Image is Now Available."
#     body: |
#       The following provisioned Image is now available in C2E:

#       AMI ID: {{ provisioned_ami_id }}
#       AMI NAME: {{ provisioned_image_name }}

#       Other Formats of the same image can be found at the following locations in the '{{ s3_bucket_name }}' S3 Bucket:

#       OVA: {{ s3_ova_full_pathname }}
#       VMDK: {{ s3_vmdk_full_pathname }}
#       VHD: {{ s3_vhd_full_pathname }}
#       QCOW2: {{ s3_qcow2_full_pathname }}

- name: All Provisioned Image Conversions COMPLETE!
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop:
    - "AMI ID: {{ provisioned_ami_id }}, AMI NAME: {{ provisioned_image_name }}"
    - "OVA: {{ s3_ova_full_pathname }}"
    - "VMDK: {{ s3_vmdk_full_pathname }}"
    - "VHD: {{ s3_vhd_full_pathname }}"
    - "QCOW2: {{ s3_qcow2_full_pathname }}"
