# The following three settings are required by DISA STIG
set -g lock-command vlock
# Enable users to manually lock a tmux session ("Ctrl + b" then "Shift + x")
bind X lock-session
set -g lock-after-time 900

# The following options are not STIG related, but make using tmux easier
# Enable mouse scrolling in a tmux window
set -g mouse on

# Set background color of active tmux window to off-white and text color to black
# set -g window-active-style bg=white,fg=black

# Start window and pane numbers at "1" instead of "0"
set -g base-index 1
setw -g pane-base-index 1

# Increase scroll history buffer to 10,000 lines
set -g history-limit 10000

# Prevent tmux server from exiting when there are no active sessions
set -s exit-empty off
