---
# tasks file for verify_s3_terminate_ec2

- name: Wait, Check every 30 seconds for 60 minutes until vmdk appears in S3 bucket
  amazon.aws.s3_object_info:
    aws_region: "{{ aws_region }}"
    bucket_name: "{{ s3_bucket_name }}"
    object_name: "{{ vmdk_full_pathname }}"
    access_key: "{{ aws_access_key }}"
    secret_key: "{{ aws_secret_key }}"
  register: s3_check
  retries: 120
  delay: 30
  until: s3_check.object_info[0].object_data is defined
  ignore_errors: false

- name: Wait, Check every 30 seconds for 60 minutes until vhd appears in S3 bucket
  amazon.aws.s3_object_info:
    aws_region: "{{ aws_region }}"
    bucket_name: "{{ s3_bucket_name }}"
    object_name: "{{ vhd_full_pathname }}"
    access_key: "{{ aws_access_key }}"
    secret_key: "{{ aws_secret_key }}"
  register: s3_check
  retries: 120
  delay: 30
  until: s3_check.object_info[0].object_data is defined
  ignore_errors: false

- name: Terminate vmdk EC2 Instance
  amazon.aws.ec2_instance:
    instance_ids: "{{ vmdk_instance_id }}"
    region: "{{ aws_region }}"
    state: terminated
    access_key: "{{ aws_access_key }}"
    secret_key: "{{ aws_secret_key }}"
    wait: true

- name: Terminate vhd EC2 Instance
  amazon.aws.ec2_instance:
    instance_ids: "{{ vhd_instance_id }}"
    region: "{{ aws_region }}"
    state: terminated
    access_key: "{{ aws_access_key }}"
    secret_key: "{{ aws_secret_key }}"
    wait: true
