---

### Add proof of provision file ###
- name: Add Provisioning File to /tmp/
  ansible.builtin.copy:
    dest: /tmp/provisioned_by_image_factory.txt
    content: |
      This file was created using the
      automated image_factory.
    mode: '0644'
    owner: root
    group: root

### Create cloud-user ###

- name: Create cloud-user if the user doesn't exist & set Temporary Password
  ansible.builtin.user:
    name: cloud-user
    shell: /bin/bash
    groups:
      - adm
      - wheel
      - systemd-journal
    append: true
    comment: "cloud-user"
    expires: -1
    password: "{{ 'Changeplease$1235' | password_hash('sha512') }}"
    state: present
    
### Enable SSH authentication with password ###

- name: Ensure PasswordAuthentication is set to yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication yes'
    state: present
    backrefs: yes

- name: Ensure ChallengeResponseAuthentication is disabled (optional but common)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?ChallengeResponseAuthentication'
    line: 'ChallengeResponseAuthentication no'
    state: present
    backrefs: yes

- name: Restart SSH service
  service:
    name: sshd
    state: restarted

### Configure cloud-init with default user cloud-user ###

      #- name: Ensure cloud-init is installed
      #ansible.builtin.package:
      #name: cloud-init
      #state: installed
    
- name: Deploy cloud.cfg template for cloud-init
  ansible.builtin.template:
    src: cloud_cfg.j2
    dest: /etc/cloud/cloud.cfg
    owner: root
    group: root
    mode: 0644

### Clean up Image ###
- name: Unregister, delete tmp files and clean cloud-init
  ansible.builtin.import_role:
    name: image_prep

