---

aws_region: us-east-2

ec2_instance_type: t2.micro
ec2_image: ami-0c7b153139eee1d57 
ec2_key_name: akalohi_aws_pem
ec2_security_group: my-security-group-1
ec2_subnet_id: subnet-0e7421b258ef5d274
ec2_instance_name: temp-instance

s3_bucket_name: akalohi-aws-bucket-1 

iam_role_name: vmimport
