---
# tasks file for create_ec2_vhd

- name: Launch EC2 Instance
  amazon.aws.ec2_instance:
    name: "{{ ec2_instance_name }}"
    key_name: "{{ ec2_key_name }}"
    instance_type: "{{ ec2_instance_type }}"
    image_id: "{{ ec2_image }}"
    count: 1
    vpc_subnet_id: "{{ ec2_subnet_id }}"
    security_group: "{{ ec2_security_group }}"
    region: "{{ aws_region }}"
    state: running
    wait: true
    network_interfaces:
      - assign_public_ip: true
  register: ec2_result

- name: Wait for instance to pass 2/2 checks using AWS CLI
  ansible.builtin.shell: |
    aws ec2 wait instance-status-ok \
    --instance-ids {{ ec2_result.instances[1].instance_id }} \
    --region {{ aws_region }}
  changed_when: false

- name: Add new EC2 IP to inventory group 'vhd_instances'
  ansible.builtin.add_host:
    name: "{{ ec2_result.instances[1].public_ip_address }}"
    groups: vhd_instances
    ec2_instance_id: "{{ ec2_result.instances[1].instance_id }}"

- name: Add vhd_instance_id and public IP to localhost as variables
  ansible.builtin.add_host:
    name: localhost
    groups: all
    vhd_instance_id: "{{ ec2_result.instances[1].instance_id }}"
    vhd_instance_public_ip: "{{ ec2_result.instances[1].public_ip_address }}"
