---
# tasks file for packer
#
- name: Set final 'provisioned_image_name' variable for circumventing idempotency
  ansible.builtin.set_fact:
    provisioned_image_name: "{{ image_name }}-{{ ansible_date_time.epoch }}"
    
- name: Create packer target directory
  ansible.builtin.file:
    path: "{{ packer_build_dir }}"
    state: directory
    owner: rh-ansible
    group: domusers
    mode: '0755'

- name: Ensure Packer Playbooks are on Worker node
  ansible.builtin.copy:
    src: packer_playbooks # This is a softlink to the actual playbooks in the top level 'packer' directory of the git repo
    dest: "{{ packer_build_dir }}"
    owner: rh-ansible
    group: domusers
    directory_mode: 0755

- name: Deploy Packer build files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ packer_build_dir }}"
    owner: rh-ansible
    group: domusers
    mode: '0644'
  loop:
    - update-packer.pkr.hcl
    - variables.auto.pkrvars.hcl

- name: Deploy packer variable template
  ansible.builtin.template:
    src: variables.pkr.hcl.j2
    dest: "{{ packer_build_dir }}/variables.pkr.hcl"
    owner: rh-ansible
    group: domusers
    mode: '0644'

- name: Run Packer Init
  ansible.builtin.shell:
    cmd: packer init .
    chdir: "{{ packer_build_dir }}"
  register: init_result
  failed_when: init_result.rc != 0
  become: false

- name: Run Packer Build
  ansible.builtin.shell: 
    cmd: packer build .  # This command will force packer to automatically load variable definitions 
    chdir: "{{ packer_build_dir }}"
  register: build_result
  failed_when: build_result.rc != 0
  become: false

- name: Show Packer Build Output
  ansible.builtin.debug:
    var: build_result.stdout_lines

- name: Get 'provisioned_ami_id' from Packer Output
  ansible.builtin.set_fact:
    provisioned_ami_id: "{{ (build_result.stdout | regex_findall('ami-[a-zA-Z0-9]+'))[1] }}" # This will pull the Provisioned AMI ID for use in conversion

- name: Show 'provisioned_ami_id' variable
  ansible.builtin.debug:
    var: provisioned_ami_id
