---
# tasks file for terminate_ec2_instances

- name: Terminate Dummy Instance
  amazon.aws.ec2_instance:
    instance_ids: "{{ dummy_ec2_instance_id }}"
    region: "{{ aws_region }}"
    state: terminated
    wait: true
    access_key: "{{ aws_access_key }}"
    secret_key: "{{ aws_secret_key }}"
    session_token: "{{ aws_session_token }}"
    validate_certs: false
  become: false
  when: dummy_ec2_instance_id is defined
