---
# tasks file for terminate_ec2_instances

- name: Terminate OVA EC2 Instance
  amazon.aws.ec2_instance:
    instance_ids: "{{ item }}"
    region: "{{ aws_region }}"
    state: terminated
    access_key: "{{ aws_access_key }}"
    secret_key: "{{ aws_secret_key }}"
    wait: true
  loop:
    - "{{ ova_instance_id }}"
    - "{{ dummy_ec2_instance_id }}"

# - name: Display exported image filename
#   ansible.builtin.debug:
#     msg: |
#       "OVA: {{ ova_full_pathname }}
      
#       VHD: {{ vhd_full_pathname }}

#       VMDK: {{ vmdk_full_pathname }}

#       QCOW2: {{ qcow2_full_pathname }}"