---
# tasks file for image_prep

- name: Universal image prep
  ansible.builtin.import_tasks:
    file: universal_prep.yml

- name: AWS specific prep
  ansible.builtin.import_tasks:
    file: aws_prep.yml


