---

# Collections needed for this playbook
#  - amazon.aws
#  - containers.podman

- hosts: localhost
  remote_user: ec2-user
  vars_files: 
    - roles/setup_runner/defaults/aws_access_credentials.yml
  roles:
    - setup_runner
    - create_ec2_vmdk

- hosts: vmdk_instances
  remote_user: ec2-user
  vars_files: 
    - roles/setup_runner/defaults/aws_access_credentials.yml
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
  roles:
    - export_ec2_to_vmdk

# - hosts: localhost
#   remote_user: ec2-user
#   vars_files: 
#     - roles/setup_runner/defaults/aws_access_credentials.yml
#   roles:
#     - create_ec2_vhd

# - hosts: vhd_instances
#   remote_user: ec2-user
#   vars_files: 
#     - roles/setup_runner/defaults/aws_access_credentials.yml
#   roles:
#     - export_ec2_to_vhd
