---

# Collections needed for this playbook
#  - amazon.aws

- name: Setup Execution Host & Import Images
  hosts: worker_node
  remote_user: rh-ansible
  tags: import_base_image
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_SESSION_TOKEN: "{{ aws_session_token }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"
  
  tasks:
    # - name: Setup Execution Host
    #   ansible.builtin.import_role:
    #     name: setup_execution_host

  - name: OVA Image Detected, Beginning OVA Import (WANDS Import Method)
    ansible.builtin.import_role:
      name: import_base_ova
    when: image_type == 'ova'
      
  - name: VMDK Image Detected, Beginning VMDK Import (C2E Import Method)
    ansible.builtin.import_role:
      name: import_base_vmdk
    when: image_type == 'vmdk'

- name: Create ec2_dummy instance from Imported AMI
  hosts: worker_node
  remote_user: rh-ansible
  tags: create_ec2_dummy 
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_SESSION_TOKEN: "{{ aws_session_token }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"

  roles:
    - create_ec2_dummy

- name: Provision Dummy Instance & create Provisioned AMI
  hosts: dummy_instance
  remote_user: ec2-user
  tags: provision_dummy_instance
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_SESSION_TOKEN: "{{ aws_session_token }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"

  roles:
    - add_provisioned_verification_file
    #- provision_dummy_instance

- name: Export Provisioned EC2 Instance to OVA, VMDK, QCOW2, VHD, & AMI Format, then Cleanup
  hosts: worker_node
  remote_user: rh-ansible
  tags: convert_images
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_SESSION_TOKEN: "{{ aws_session_token }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"
    
  roles:
    - export_ec2_dummy_to_ova
    - verify_ova_export
    - extract_vmdk_from_ova
    - convert_vmdk_to_vhd_qcow2
    - upload_files_to_s3
    - create_provisioned_ami
    - cleanup_ami_snapshots
    - terminate_ec2_instances
    - cleanup_execution_host

  
