[ec2-user@ip-10-0-5-26 playbooks]$ anp convert_images.yml 
[WARNING]: Collection amazon.aws does not support Ansible version 2.15.3

PLAY [Setup Execution Host and Create two EC2 Instances for OVA & VHD Export] ************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************
[WARNING]: Platform linux on host 3.132.231.72 is using the discovered Python interpreter at /usr/bin/python3.9, but future installation of another Python interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-core/2.15/reference_appendices/interpreter_discovery.html for more information.
ok: [3.132.231.72]

TASK [setup_execution_host : Install pip and awscli] *************************************************************************************************************************************************************
ok: [3.132.231.72]

TASK [setup_execution_host : Install boto3 and botocore (AWS SDK)] ***********************************************************************************************************************************************
ok: [3.132.231.72]

TASK [setup_execution_host : Create AWS credentials directory] ***************************************************************************************************************************************************
ok: [3.132.231.72]

TASK [setup_execution_host : Configure AWS credentials] **********************************************************************************************************************************************************
ok: [3.132.231.72]

TASK [setup_execution_host : Configure AWS region] ***************************************************************************************************************************************************************
ok: [3.132.231.72]

TASK [setup_execution_host : Set the 'execution_host_ip' Variable Dynamically] ***********************************************************************************************************************************
changed: [3.132.231.72]

TASK [create_ec2_dummy : Launch EC2 Dummy Instance for OVA Export] ***********************************************************************************************************************************************
[WARNING]: packaging.version Python module not installed, unable to check AWS SDK versions
changed: [3.132.231.72]

TASK [create_ec2_dummy : Wait for instance to pass 2/2 checks using AWS CLI] *************************************************************************************************************************************
ok: [3.132.231.72]

TASK [create_ec2_dummy : Set 'dummy_ec2_instance_id' variable] ***************************************************************************************************************************************************
ok: [3.132.231.72]

PLAY [Export OVA from Dummy Instance] ****************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************
ok: [3.132.231.72]

TASK [export_ec2_to_ova : Export EC2 Instance to OVA (Command Module Path)] **************************************************************************************************************************************
changed: [3.132.231.72]

TASK [export_ec2_to_ova : Set 'exported_image_id' and 'ova_full_pathname' variables (Command Module Path)] *******************************************************************************************************
ok: [3.132.231.72]

TASK [export_ec2_to_ova : Display exported OVA image filename] ***************************************************************************************************************************************************
ok: [3.132.231.72] => {
    "msg": "OVA Filename: export-i-31be5ee20cfda3f3t.ova"
}

PLAY [Wait for OVA Export to complete and appear in S3 Bucket] ***************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************
ok: [3.132.231.72]

TASK [verify_ova_export : Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket] ************************************************************************************************************
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (120 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (119 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (118 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (117 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (116 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (115 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (114 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (113 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (112 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (111 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (110 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (109 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (108 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (107 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (106 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (105 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (104 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (103 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (102 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (101 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (100 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (99 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (98 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (97 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (96 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (95 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (94 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (93 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (92 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (91 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (90 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (89 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (88 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (87 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (86 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (85 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (84 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (83 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (82 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (81 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (80 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (79 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (78 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (77 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (76 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (75 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (74 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (73 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (72 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (71 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (70 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (69 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (68 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (67 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (66 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (65 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (64 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (63 retries left).
FAILED - RETRYING: [3.132.231.72]: Wait, Check every 30 seconds for 60 minutes until OVA appears in S3 bucket (62 retries left).
ok: [3.132.231.72]

PLAY [Create VMDK, VHD and QCOW2 Images from OVA] ****************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************
ok: [3.132.231.72]

TASK [extract_vmdk_from_ova : Create /tmp/image_conversion Directory] ********************************************************************************************************************************************
changed: [3.132.231.72]

TASK [extract_vmdk_from_ova : GET OVA from S3 Bucket] ************************************************************************************************************************************************************
changed: [3.132.231.72]

TASK [extract_vmdk_from_ova : Unarchive OVA TAR file] ************************************************************************************************************************************************************
changed: [3.132.231.72]

TASK [extract_vmdk_from_ova : Find VMDK file in /tmp/image_conversion/ Directory] ********************************************************************************************************************************
ok: [3.132.231.72]

TASK [extract_vmdk_from_ova : Set 'path_to_vmdk' variable] *******************************************************************************************************************************************************
ok: [3.132.231.72]

TASK [convert_vmdk_to_vhd_qcow2 : set 'path_to_vhd' & 'path_to_qcow2' variable] **********************************************************************************************************************************
ok: [3.132.231.72]

TASK [convert_vmdk_to_vhd_qcow2 : Ensure qemu-img package is installed] ******************************************************************************************************************************************
changed: [3.132.231.72]

TASK [convert_vmdk_to_vhd_qcow2 : Convert VMDK to VHD and QCOW2 (Command Module)] ********************************************************************************************************************************
changed: [3.132.231.72] => (item={'input_format': 'vmdk', 'output_format': 'vpc', 'source_file': '/tmp/image_conversion/export-i-31be5ee20cfda3f3t-disk-1.vmdk', 'destination_file': '/tmp/image_conversion/export-i-31be5ee20cfda3f3t.vhd'})
changed: [3.132.231.72] => (item={'input_format': 'vmdk', 'output_format': 'qcow2', 'source_file': '/tmp/image_conversion/export-i-31be5ee20cfda3f3t-disk-1.vmdk', 'destination_file': '/tmp/image_conversion/export-i-31be5ee20cfda3f3t.qcow2'})

TASK [upload_files_to_s3 : PUT VMDK, VHD, & QCOW2 files into S3 Bucket] ******************************************************************************************************************************************
changed: [3.132.231.72] => (item={'local_source_file': '/tmp/image_conversion/export-i-31be5ee20cfda3f3t-disk-1.vmdk', 's3_destination_path': 'Exports/vmdk/export-i-31be5ee20cfda3f3t.vmdk'})
changed: [3.132.231.72] => (item={'local_source_file': '/tmp/image_conversion/export-i-31be5ee20cfda3f3t.vhd', 's3_destination_path': 'Exports/vhd/export-i-31be5ee20cfda3f3t.vhd'})
changed: [3.132.231.72] => (item={'local_source_file': '/tmp/image_conversion/export-i-31be5ee20cfda3f3t.qcow2', 's3_destination_path': 'Exports/qcow2/export-i-31be5ee20cfda3f3t.qcow2'})

TASK [upload_files_to_s3 : Set S3 Export Image Pathname Variables] ***********************************************************************************************************************************************
ok: [3.132.231.72]

PLAY [Cleanup AMIs, Snapshots, Instances, and Execution Host] ****************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************
ok: [3.132.231.72]

TASK [cleanup_ami_snapshots : Gather information about an AMI with 'AMI Name' equal to "export-i-31be5ee20cfda3f3t"] *********************************************************************************************
ok: [3.132.231.72]

TASK [cleanup_ami_snapshots : Display Associated AMI ID] *********************************************************************************************************************************************************
ok: [3.132.231.72] => {
    "associated_ami_info.images[0].image_id": "ami-008689a7a8b6579fc"
}

TASK [cleanup_ami_snapshots : Deregister AMI & Delete associated Snapshot] ***************************************************************************************************************************************
changed: [3.132.231.72]

TASK [terminate_ec2_instances : Terminate OVA EC2 Instances] *****************************************************************************************************************************************************
changed: [3.132.231.72] => (item=i-03db6d7aa0a85f66d)

TASK [cleanup_execution_host : Remove /tmp/image_conversion/ directory and its contents] *************************************************************************************************************************
changed: [3.132.231.72]

TASK [cleanup_execution_host : All Image Conversions COMPLETE!] **************************************************************************************************************************************************
ok: [3.132.231.72] => (item=OVA: Exports/ova/export-i-31be5ee20cfda3f3t.ova) => {
    "msg": "OVA: Exports/ova/export-i-31be5ee20cfda3f3t.ova"
}
ok: [3.132.231.72] => (item=VMDK: Exports/vmdk/export-i-31be5ee20cfda3f3t.vmdk) => {
    "msg": "VMDK: Exports/vmdk/export-i-31be5ee20cfda3f3t.vmdk"
}
ok: [3.132.231.72] => (item=VHD: Exports/vhd/export-i-31be5ee20cfda3f3t.vhd) => {
    "msg": "VHD: Exports/vhd/export-i-31be5ee20cfda3f3t.vhd"
}
ok: [3.132.231.72] => (item=QCOW2: Exports/qcow2/export-i-31be5ee20cfda3f3t.qcow2) => {
    "msg": "QCOW2: Exports/qcow2/export-i-31be5ee20cfda3f3t.qcow2"
}

PLAY RECAP *******************************************************************************************************************************************************************************************************
3.132.231.72               : ok=34   changed=12   unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 