---

- hosts: execution_host
  become: false
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_SESSION_TOKEN: "{{ aws_session_token }}"
  tasks:

  - name: Start import image task
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop:
      - "{{ s3_bucket_name }}"
      - "{{ s3_key }}"
      - "{{ aws_region }}"
      - "{{ image_type }}"

  - name: Image is an ova
    ansible.builtin.debug:
      var: s3_key
    when: image_type == 'ova'

  - name: Image is a vmdk
    ansible.builtin.debug:
      var: s3_key
    when: image_type == 'vmdk'

  