---

- name: "Transfer VMDK image from the Worker-Node {{ vmdk_source_dir }} to S3://{{ s3_bucket_name }}/Imports/"
  hosts: worker_node
  remote_user: rh-ansible
  become: true
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_SESSION_TOKEN: "{{ aws_session_token }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"
  
  roles:
    - transfer_vmdk_to_s3
    
